name = "spin-mama-login-org"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-login.org"
HMAC_KEY = "2a5ce07495d7c177795ca9093680ffd6504ea623fc7eaf5c95c5d85a9278fdc2"
COOKIE_NAME = "8ol"
PLAY_PATH = "launch"
BUTTON_ID = "p76a4edfaba445229e049235f0f31e18b"
GATE_SALT = "f4be014f129c2e89"
